### ISSUE TITLE
InvalidBucketAclWithObjectOwnership error due to AccessControl: LogDeliveryWrite in S3LoggingBucket block

### ISSUE THREAD

**Issue by jtcastillo** [aws-samples/network-access-analyzer-multi-account-analysis#45]
I've been trying to deploy the naa-resources.yaml stack for a little while now and kept running into an error when trying to create the S3LoggingBucket. The cloud formation stack always fails on the S3LoggingBucket step with the error *InvalidBucketAclWithObjectOwnership* - Bucket cannot have ACLs set with ObjectOwnership's BucketOwnerEnforced setting. It doesn't matter if the bucket is new or one I've already created with object ownership manually set to 'Bucket owner preferred' or 'Object writer'. Reading through the S3LoggingBucket block, this seems to be caused due to `AccessControl: LogDeliveryWrite`. By removing that line, I am able to run the CloudFormation stack, but I am wondering if there are any implications to removing that. Should the stack still function as expected?

```
  S3LoggingBucket:
    Type: 'AWS::S3::Bucket'
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W35
            reason: "S3 access logging is not enable as this is the logging bucket"
    Properties:
      AccessControl: LogDeliveryWrite
      BucketName: !Sub "${BucketName}-accesslogs-${AWS::AccountId}-${AWS::Region}"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"
      LifecycleConfiguration:
        Rules:
        - Id: LoggingLifeCycle
          Status: Enabled
          ExpirationInDays: '180'
          NoncurrentVersionExpirationInDays: '180'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: "Name"
          Value: !Sub "${BucketName}-access-logs-${AWS::AccountId}-${AWS::Region}"
```
